export const environment = {
  production: true,

  baseUrl:'https://hrms.fossgentechnologies.in/api/api',
  //baseUrl:' http://localhost:8082/api/',
  login: '/v1/login' ,
  registration:'/v1/registration',
  ragistercandidate: '/v1/registerCandidate',
  uploadSalarySlips:  '/v1/uploadPaymentSlipPdf',
  getAllUsers: '/v1/getUsers',
  createHolidays: '/v1/createHolidays',
  bulkHolidayUpload :'/v1/uploadBulkHolidayFile',
  getAllHolidays : '/v1/upcomingHolidays',
  addLeaves: '/v1/addLeaves',
  uploadForm16: '/v1/uploadForm16',
  getFile: '/v1/viewform16',
  getAllInvestmentDeclarationByUsers: '/v1/getAllInvestmentDeclarationByUsers',
  uploadInvestmentDeclaration: '/v1/uploadInvestmentDeclaration',
  deleteInvestmentDeclaration: '/v1/deleteInvestmentDeclaration',
  uploadBulkUserRegistationFile: '/v1/uploadBulkUserRegistationFile',
  getAllExitFormByUsers: '/v1/getAllExitFormByUsers',
  uploadExitForm: '/v1/uploadExitForm',
  deleteExitForm: '/v1/deleteExitForm',
  uploadEmployeeHierarchy: '/v1/uploadEmployeeHierarchy',
  deleteEmployeeHierarchy: '/v1/deleteEmployeeHierarchy',
  paymentSlipPDF : '/v1/downloadPaymentSlip',
  signIn: '/v1/signInSignOut',
  loggedUserId: '/v1/loggedUserId',
  viewSwipe: '/v1/getSwipeDetails',
  uploadExitFormByUser: '/v1/uploadExitFormByUser',
  applyEmployeeLeaves:"/v1/applyEmployeeLeaves",
  getAllBalanceLeaves:"/v1/getAllLeaves",
  getLeaveStatus: "/v1/getAllLeaveStatusById/",
  viewform16: "/v1/viewform16",
  uploadInvestmentDecByUSer:"/v1/uploadInvestmentDeclarationByUser",
  downlodform16: '/v1/viewform16',
  getAllUserPersonalDtls: '/v1/getAllUserPersonalDtls',
  getAllLeavesList:'/v1/getAllLeavesList',
  employeeLeave:'/v1/allLeaves',
  addTask:'/v1/task',
  allTask:'/v1/allTask',
  updateTask:'/v1/updateTaskStatus',
  employeeDetails:'/v1/employeeDetails',
  employeePersonalDtls:'/v1/employeePersonalDtls',
  uploadCertificatePdf:'/v1/uploadCertificatePdf',
  viewEmployeeCertificate:'/v1/viewEmployeeCertificate',
  exitFormFinalDate: '/v1/exitFormFinalDate',
  deleteForm16: '/v1/form16',
  deleteInvestmentDeclarationOfUser:'/v1/deleteInvestmentDeclarationOfUser',
  deleteExitFormOfUser:'/v1/deleteExitFormOfUser',
  postEmployeeData:'/v1/userPersonalDtls',
  getSignInSignOut:'/v1/getSignInSignOut',
  updateStatus:'/v1',
  updateStatus1:'/status/hrReason',
  getUserTask:'/v1/perticulartask',
  employeeHierarchyPDF:'/v1/getEmployeeHierarchy',
  getInvestmentDeclarationFormat : '/v1/getInvestmentDeclarationFormat',
  downloadExitForm : '/v1/getExitForm'
};
